## qn.5


In [1]:
import numpy as np

In [2]:
import numpy as np

In [3]:
x = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print(x)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


## i) Inversion of a matrix

In [4]:
import numpy as np
x= np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print(x)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [5]:
x_transpose = np.transpose(x)
print(x_transpose)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


## ii) determinants of a matrix

In [6]:
determinant = np.linalg.det(x)
print(determinant)

0.2299999999999999


## iii) decomposing of a matrix

In [7]:
x_decompose = np.linalg.svd(x)
print(x_decompose)

SVDResult(U=array([[-0.43721717,  0.85359707, -0.28321933],
       [-0.59931898, -0.51133314, -0.61591816],
       [-0.67056536, -0.09955128,  0.73514055]]), S=array([2.04100779, 0.82188052, 0.13711169]), Vh=array([[-0.43721717, -0.59931898, -0.67056536],
       [ 0.85359707, -0.51133314, -0.09955128],
       [-0.28321933, -0.61591816,  0.73514055]]))


## iv) transforms of a matrix

In [8]:
x_transform = np.shape(x)
print(x_transform)

(3, 3)
